services:
  # ðŸŸ© FRONTEND: React + Vite
  frontend:
    build: ./Client
    container_name: vite-frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./Client:/app
      - /app/node_modules
    depends_on:
      - backend

  # ðŸŸ¦ BACKEND: Node.js + Express
  backend:
    build: ./Server
    container_name: node-backend
    ports:
      - "3000:3000"
    env_file:
      - ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
    
      
